Transfer a file to your server

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,8 +1,28 @@
 #!/usr/bin/env bash
-# Bash script that transfers a file from our client to a server
-if [ "$#" -eq 4 ];
+# A script that transfers a file from our client to a server
+
+if [ $# -lt 4 ]
 then
-    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
+	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+	exit 1
+fi
+
+# Assign parameters to varables
+
+PATH_TO_FILE=$1
+IP=$2
+USERNAME=$3
+PATH_TO_SSH_KEY=$4
+
+# Disable strict host key check
+
+sco -o "StrickHostKeyChecking=no" -i "PATH_TO_SSH_KEY" "PATH_TO_FILE" "USERNAME@$IP:~/"
+
+# Check if file transfer was successful
+
+if [ $? -eq 0 ]
+then
+	echo "FILE TRANSFER WAS SUCCESSFUL"
 else
-    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+	echo "FILE TRANSFER FAILED"
 fi
